Hw1
aytel/javaHSE19 pull request #1
Opened 2019-01-17 19:23 UTC by aytel

2019-01-21 12:17 UTC, jzuken requested changes

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyHashTable.java
> +    private final double ALPHA = 0.5;
не очень понятное имя

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyHashTable.java
> +        this.array = new MyListPairStringString[1];
почему 1? лучше сразу создать какого-то вменяемого размера, и постоянно не перестраивать

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyHashTable.java
> +public class MyHashTable {
javadoc потерялся

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyHashTable.java
> +    MyHashTable() {
а чего оно package-level?

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyHashTable.java
> +     * @param key
описание потерялось. тут и много где ещё

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyHashTable.java
> +     * @return number of elements in table
в случае совсем простых методов типа этого лучше явно писать то, что метод делает, без тегов

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyHashTable.java
> +            size--;
то есть оно только растёт и не сжимается?

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyHashTable.java
> +        return key.hashCode() % array.length;
а кто-то гарантирует, что hashCode() вернёт неотрицательное значение?

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyHashTable.java
> +        String ret = array[hash(key)].put(key, val);
не надо экономить на сокращении имён. код читается обычно сильно больше раз, чем пишется, и разбираться в нём надо как можно меньше времени

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyHashTable.java
> +        MyListPairStringString[] newArray = new MyListPairStringString[2 * array.length];
вообще если тип очевиден из правой части, лучше писать var

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyHashTable.java
> +    public String put(String key, String val) {
а val тоже может быть null

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyListPairStringString.java
> +public class MyListPairStringString {
а этот класс паблик, потому что реально кому-то кроме хеш-таблицы нужен?

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyListPairStringString.java
> +        if (Objects.equals(node.getKey(), key)) {
а `node.getKey().equals(key)` чем не угодил?

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyHashTable.java
> +package HashTable;
это не очень похоже на уникальные имена пакетов, про которые я говорил на прошлой паре

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyListPairStringString.java
> +        private Node next, prev;
лучше не объявлять несколько полей в одной строке

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyListPairStringString.java
> +public class MyListPairStringString {
ну и да, вообще это список, а называется оно почему-то StringString

2019-01-21 12:17 UTC, jzuken commented on hw1/src/main/java/HashTable/MyHashTable.java
> +    /**
однострочные доки лучше писать как `/** ... */`

2019-01-21 12:17 UTC, jzuken commented on hw1/src/test/java/HashTable/MyHashTableTest.java
> +        MyHashTable myHashTable = new MyHashTable();
вообще имеет смысл использовать @BeforeEach для инициализации хеш-таблицы, а то копипаста

2019-01-21 12:17 UTC, jzuken commented on hw1/src/test/java/HashTable/MyHashTableTest.java
> +        MyHashTable myHashTable = new MyHashTable();
вообще имеет смысл использовать @BeforeEach для инициализации хеш-таблицы, а то копипаста

2019-01-21 12:56 UTC, aytel commented on hw1/src/main/java/HashTable/MyHashTable.java
> +            size--;
Что именно? MyListPairStringString сжимается, мы из него выкидываем. А число бакетов действительно не уменьшается ни при remove'е, ни при очищении таблицы.

2019-01-21 13:07 UTC, aytel commented on hw1/src/main/java/HashTable/MyListPairStringString.java
> +        if (Objects.equals(node.getKey(), key)) {
Ну, мне нагляднее, не когда у объекта вызывается метод, а когда я вижу equals в начале, а потом рядом аргументы -- что именно сравниваю. Это критично?

2019-01-21 13:12 UTC, aytel commented on hw1/src/main/java/HashTable/MyListPairStringString.java
> +public class MyListPairStringString {
Переименовал, но меня гнетут тяжкие сомнения, что всё ещё не классно. Можете подсказать, как его адекватно назвать?

2019-01-21 15:42 UTC, jzuken commented on hw1/src/main/java/HashTable/MyHashTable.java
> +            size--;
ну вот и я про то. от clear() ожидаемое поведение было бы такое, что она возвращает размер таблицы к исходному

2019-01-21 15:43 UTC, jzuken commented on hw1/src/main/java/HashTable/MyListPairStringString.java
> +        if (Objects.equals(node.getKey(), key)) {
ну да, вы же на объектно-ориентированном языке програмируете. а вы описываете чисто процедурный стиль

2019-01-21 15:52 UTC, aytel commented on hw1/src/main/java/HashTable/MyHashTable.java
> +            size--;
Окей, fixed

2019-03-07 11:58 UTC, jzuken commented
конфликт с мастером

2019-03-07 12:04 UTC, jzuken commented on hw1/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
этот файл не надо выкладывать, это настройки редактора

2019-03-07 12:04 UTC, jzuken commented on hw1/src/main/java/com/aytel/HashTable/MyHashTable.java
> +    public MyHashTable(double LOAD_FACTOR, int capacity) throws IllegalArgumentException {
почему он именуется как константа?
-0.5

и да, исключения тоже надо документировать

2019-03-07 12:04 UTC, jzuken commented on hw1/src/main/java/com/aytel/HashTable/MyHashTable.java
> +        for (var cur : oldArray) {
не надо таких сокращений, пожалуйста. просил же уже
-1

2019-03-07 12:04 UTC, jzuken commented on hw1/src/main/java/com/aytel/HashTable/MyListOfPairsStringString.java
> +    private class Node {
лучше убирать вложенные классы в конец объемлющих

2019-03-07 12:04 UTC, jzuken commented on hw1/src/main/java/com/aytel/HashTable/MyListOfPairsStringString.java
> +        public void setNext(Node next) {
объемлющий класс имеет доступ ко всем полям вложенных, так что смысла в этих аксессорах не особо

2019-03-07 12:04 UTC, jzuken commented on hw1/src/main/java/com/aytel/HashTable/MyListOfPairsStringString.java
> +    MyListOfPairsStringString() {}
модификатор доступа потерялся

2019-03-07 12:04 UTC, jzuken commented on hw1/src/main/java/com/aytel/HashTable/MyHashTable.java
> +            for (Entry<String, String> entry = cur.pop(); entry != null; entry = cur.pop()) {
а вот тут идеальное место для использования var

2019-03-16 09:32 UTC, aytel commented on hw1/src/main/java/com/aytel/HashTable/MyListOfPairsStringString.java
> +    MyListOfPairsStringString() {}
Но он ведь должен быть package-private? Я не хочу, чтобы он торчал совсем наружу, но в пакете мне нужно его использовать. Собственно, сам класс тоже package-private.

2019-03-16 14:46 UTC, jzuken commented on hw1/src/main/java/com/aytel/HashTable/MyListOfPairsStringString.java
> +    MyListOfPairsStringString() {}
ок

2019-03-16 15:01 UTC, jzuken commented
-2 балла, кстати, за неисправленные в течение недели замечания

2019-03-16 15:02 UTC, merged