hw7.java
aytel/javaHSE19 pull request #11
Opened 2019-04-30 17:57 UTC by aytel

2019-05-03 14:59 UTC, jzuken requested changes

2019-05-03 14:59 UTC, jzuken commented on hw7.java/src/main/java/com/aytel/LightFuture.java
> +    /** Waits for calculating and returns the result. */
бросаемые исключения тоже надо документировать
-0.5

2019-05-03 14:59 UTC, jzuken commented on hw7.java/src/main/java/com/aytel/ThreadPool.java
> +        Arrays.stream(this.threads).forEach(Thread::interrupt);
давайте заджойним все потоки ещё

2019-05-03 14:59 UTC, jzuken commented on hw7.java/src/main/java/com/aytel/ThreadPool.java
> +                synchronized (tasks) {
а зачем тут две синхронизации?

2019-05-03 14:59 UTC, jzuken commented on hw7.java/src/main/java/com/aytel/ThreadPool.java
> +            return task;
unchecked assignment

2019-05-03 14:59 UTC, jzuken commented on hw7.java/src/test/java/com/aytel/ThreadPoolTest.java
> +public class ThreadPoolTest {
хорошо бы тесты на все возможные сценарии. работа thenApply(), например, вообще не проверяется
-1

2019-05-15 18:38 UTC, aytel commented on hw7.java/src/main/java/com/aytel/ThreadPool.java
> +            return task;
А где именно тут что-то unchecked? task вроде не просто Task, а именно Task<K>, так что LightFuture<K> я возвращаю честно.

2019-05-17 14:38 UTC, jzuken commented on hw7.java/src/main/java/com/aytel/ThreadPool.java
> +            return task;
так а вы идею откройте, она же подсвечивает это место тоже

2019-05-17 14:58 UTC, aytel commented on hw7.java/src/main/java/com/aytel/ThreadPool.java
> +            return task;
Ну, нет, у меня точно не подсвечивает. Да и не должна, тут же всё строго.
Вы не знаете, как это тогда фиксить?

2019-05-17 15:02 UTC, jzuken commented on hw7.java/src/main/java/com/aytel/ThreadPool.java
> +            return task;
для начала, написать своё имя в профиле на гитхабе где-нибудь, а то я даже не знаю, где ваш код на диске искать

2019-05-21 14:53 UTC, aytel commented on hw7.java/src/main/java/com/aytel/ThreadPool.java
> +            return task;
Я вроде нашёл, откуда может быть unchecked cast, сейчас пофиксил

2019-06-06 07:28 UTC, merged