Hw8.java
aytel/javaHSE19 pull request #13
Opened 2019-05-21 22:49 UTC by aytel

2019-05-31 14:42 UTC, RamSaw requested changes
@aytel домашку проверил, жду исправлений или контраргументов.

2019-05-31 14:42 UTC, RamSaw commented on hw8.java/build.gradle
> +plugins {
сделайте, пожалуйста, gradlew исполняемым файлом.

2019-05-31 14:42 UTC, RamSaw commented on hw8.java/build.gradle
> +    id 'java'
также travis пофиксите пожалуйста

2019-05-31 14:42 UTC, RamSaw commented on hw8.java/build.gradle
> +mainClassName = 'com.aytel.Main'
jar не запускается

2019-05-31 14:42 UTC, RamSaw commented on hw8.java/settings.gradle
> +rootProject.name = 'hw'
По игре и функциональности замечаний нет, все ок.

2019-05-31 14:42 UTC, RamSaw commented on hw8.java/src/main/java/com/aytel/Cannon.java
> +        gc.fillRect(x - (BASE_WIDTH >> 1), y - (BASE_HEIGHT >> 1), BASE_WIDTH, BASE_HEIGHT);
">>" типа "/ 2". Обычно в плюсах такое только вижу.

2019-05-31 14:42 UTC, RamSaw commented on hw8.java/src/main/java/com/aytel/IntrusiveList.java
> +class IntrusiveList<T extends IntrusiveList.IntrusiveContainer> implements Iterable<T> {
а почему именно интрузивные и почему реализовывать самому?

2019-05-31 14:42 UTC, RamSaw commented on hw8.java/src/main/java/com/aytel/IntrusiveList.java
> +    static abstract class IntrusiveContainer<K extends IntrusiveContainer<K>> {
а зачем abstract? просто чтобы никто не создал instance и все только наследовались?

2019-05-31 14:42 UTC, RamSaw commented on hw8.java/src/main/java/com/aytel/Main.java
> +        finalText.setY(HEIGHT >> 1);
давайте может по нормальному напишем. ну очень уж странно смотрится, мы же не для микропроцессоров код пишем, где наносекунды важны.

2019-06-09 00:08 UTC, aytel commented on hw8.java/src/main/java/com/aytel/IntrusiveList.java
> +class IntrusiveList<T extends IntrusiveList.IntrusiveContainer> implements Iterable<T> {
Потому что хочется при уничтожении объекта чтобы он сам себя из списка выпиливал, поэтому интрузивные. А самому -- честно говоря, в голову не пришло гуглить, просто легче написать оказалось.

2019-06-09 00:10 UTC, aytel commented on hw8.java/src/main/java/com/aytel/IntrusiveList.java
> +    static abstract class IntrusiveContainer<K extends IntrusiveContainer<K>> {
Ну да. IntrusiveContainer сам по себе ничем не является, элементы, которые я хочу хранить в IntrusiveList, должны сами этими контейнерами являться.

2019-06-09 00:43 UTC, aytel commented on hw8.java/build.gradle
> +mainClassName = 'com.aytel.Main'
Не уверен, что это нормально, но у меня тоже не получилось, и я [нагуглил](https://stackoverflow.com/questions/52761836/javafx-packaging-noclassdeffounderror), что это проблема с javaFX, который не поддерживается по умолчанию в JDK 11, так что остаётся запуск через gradle. Если всё-таки можно собрать рабочий .jar, то самому интересно, как.

2019-06-09 08:21 UTC, RamSaw commented on hw8.java/build.gradle
> +mainClassName = 'com.aytel.Main'
`
jar {
    manifest {
        attributes 'Main-Class': 'com.example.cannon.CannonApplicationLauncher'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
`

Можно вот так к примеру. Или указать еще зависимости javafx в dependencies как runtime зависимости.

2019-06-09 08:24 UTC, RamSaw commented
@aytel все ок. Только расскажите, что это за коммит 7b1d220 ("switch") и что в нем произошло. И зачем вы коммитили как Unknown (и это вообще законно?).
@jzuken

2019-06-13 19:01 UTC, aytel commented
> @aytel все ок. Только расскажите, что это за коммит [7b1d220](https://github.com/aytel/javaHSE19/commit/7b1d22004ab0ba39f12f149ce33c9d87d1488e8a) ("switch") и что в нем произошло. И зачем вы коммитили как Unknown (и это вообще законно?).
> @jzuken

Это я дурак и не умею пользоваться гитом, а надо было сменить бранч)
Поэтому просто коммитил всё, что есть
Unknown, видимо, потому, что через консоль, а не IDE, хотя, конечно странно, я всё равно там вводил логин-пароль

2019-06-14 08:27 UTC, merged