Hw2
aytel/javaHSE19 pull request #2
Opened 2019-01-24 01:48 UTC by aytel

2019-02-11 09:24 UTC, jzuken requested changes

2019-02-11 09:24 UTC, jzuken commented on hw2/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
этот файл не надо выкладывать, это настройки вашего редактора

2019-02-11 09:24 UTC, jzuken commented on hw2/src/main/java/com/aytel/Trie/Trie.java
> +    private class Node {
это лучше в конец класса убирать

2019-02-11 09:24 UTC, jzuken commented on hw2/src/main/java/com/aytel/Trie/Trie.java
> +        Node(){}
и зачем он тут такой?

2019-02-11 09:24 UTC, jzuken commented on hw2/src/main/java/com/aytel/Trie/Trie.java
> +        void incSize() {
неуместные сокращения
-0.5

2019-02-11 09:24 UTC, jzuken commented on hw2/src/main/java/com/aytel/Trie/Trie.java
> +        boolean getEnd() {
раз уж у вас вложенный класс, смысл в этих геттерах-сеттерах для полей?

2019-02-11 09:24 UTC, jzuken commented on hw2/src/main/java/com/aytel/Trie/Trie.java
> +            var isEnd = (byte)(this.end ? 1 : 0);
вот эта строчка ломает мозг. по имени переменной это явно boolean, а справа число, преобразуемое к байту. и ещё var слева. это скорее как делать не надо

2019-02-11 09:24 UTC, jzuken commented on hw2/src/main/java/com/aytel/Trie/Trie.java
> +    public Trie(){}
а смысл в таком конструкторе?

2019-02-11 09:24 UTC, jzuken commented on hw2/src/main/java/com/aytel/Trie/Trie.java
> +    public boolean add(String val) throws IllegalArgumentException {
ну вообще IllegalArgumentException это непроверяемое исключение, его необязательно указывать в сигнатуре. но я бы оставил

2019-02-11 09:24 UTC, jzuken commented on hw2/src/main/java/com/aytel/Trie/Trie.java
> +    public boolean remove(String val) throws IllegalArgumentException {
опять же, неуместные сокращения

2019-02-11 09:24 UTC, jzuken commented on hw2/src/main/java/com/aytel/Trie/Trie.java
> +            throw new IllegalArgumentException("value must be not null");
и кто такой этот value? представьте, что вы получите такое сообщение в стектрейсе, ничего не понятно же будет

2019-02-11 09:24 UTC, jzuken commented on hw2/src/test/java/com/aytel/Trie/TrieTest.java
> +        assertThrows(IllegalArgumentException.class, () -> trie.add(null));
тесты на исключения лучше отдельно делать

2019-02-11 09:24 UTC, jzuken commented on hw2/src/test/java/com/aytel/Trie/TrieTest.java
> +    void serialization() throws IOException {
ну по факту этот тест проверяет, что сериализатор и десериализатор работают одинаково. и если там, например, будет одинаковая симметричная ошибка, то вы этого не поймаете. хочется отдельные тесты проверку каждого

2019-02-11 19:42 UTC, aytel commented on hw2/src/main/java/com/aytel/Trie/Trie.java
> +        Node(){}
В Trie пустой конструктор действительно не нужен, но у Node же есть ещё конструктор. Если этот убрать, ничего не работает?

2019-02-11 19:52 UTC, aytel commented on hw2/src/main/java/com/aytel/Trie/Trie.java
> +        void incSize() {
inc и dec разве не общепринятые сокращения, понятные всем? настолько общепринятые, что используются в качестве функций/команд в Паскале и Ассемблере. как тогда различать, что такое уместные, а что нет? читаемость кода не страдает, если оно настолько очевидное, а может даже становится лучше, раз уменьшается объём
исправлю сейчас, но это правда было не очевидно

2019-02-12 09:49 UTC, jzuken commented on hw2/src/main/java/com/aytel/Trie/Trie.java
> +        Node(){}
да, для ноды скорее всего пустой конструктор имеет смысл

2019-02-12 09:51 UTC, jzuken commented on hw2/src/main/java/com/aytel/Trie/Trie.java
> +        void incSize() {
читаемость кода в ассемблере это отдельная история :)
а inc вполне может быть сокращением и от increase, и от increment, что по сути своей разные действия. хотелось бы, чтобы в коде не было двусмысленности

2019-03-07 09:35 UTC, jzuken commented
конфликт с мастером

2019-03-16 15:02 UTC, merged