Hw3.java
aytel/javaHSE19 pull request #6
Opened 2019-02-14 20:59 UTC by aytel

2019-02-23 20:57 UTC, RamSaw requested changes
@aytel домашку проверил. Жду исправлений или контраргументов к замечаниям. В целом мне понравилось, круто, что сделали удаление и инвалидацию итераторов, еще круто, что красиво выразили двойственные операции через descendingTreap. Добавьте тестов, исправьте замечания и смержим.

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/gradlew
> +#!/usr/bin/env sh
У Вас этот gradlew не executable почему-то, приходится самому выставлять влаг. Пофиксите, пожалуйста.

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JListNode.java
> +class JListNode<T> {
Я бы сделал этот класс вложенным. Он же только для вашего Tree Set годится.

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +
Зачем пропускаете строчку? Так делают многие, но я не понимаю зачем, это же не улучшает читаемость кода...

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +    private boolean inverted;
Я начинаю читать код и по-моему все поля, за исключением компаратора неочевидные, давайте добавим краткие джавадоки о том, зачем они нужны. Лучше джавадоки добавим ко всем конструкторам. А к полям можно не добавлять.

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +        comparator = (T a, T b) -> ((Comparable<T>)a).compareTo(b);
А что если T не Comparable? Добавьте тестов на это. И задумайтесь, везде ли здесь T или может можно указать более общий тип?

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +    private boolean chooseTop(@NotNull Node first, @NotNull Node second) {
Как-то неочевидно, что chooseTop возвращается boolean, может лучше ноду возвращать выбранную или переименовать метод?

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +    public JTreap(@NotNull Comparator<T> comparator) {
Похоже вы не тестируете этот конструктор...

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +            return infoStorage.root.contains((T)element);
Не надо так кастовать, надо сначала проверить, что это инстанc типа T. Ниже также.

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JMyTreeSet.java
> +public interface JMyTreeSet<E> extends Set<E> {
Все методы в этом интерфейсе надо протестировать, тесты не на все есть.

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JListNode.java
> +
Пожалуйста, форматируйте аккуратно пустые строки. Это же не так сложно. Предлагаю удалить эту пустую строку.

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +        int randomValue = (new Random()).nextInt();
Рандом каждый раз, наверное, не стоит создавать. У него же метод еще и говорит, что это nextInt, значит предполагается, что его несколько раз вызывают.

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +                    next = null;
Строчка не имеет смысла

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +            boolean direction;
Давайте сделаем enum, потому что direction это все же не boolean.

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +        class baseIterator implements Iterator<T> {
классы с большой буквы всегда называются

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +                    JTreap.this.remove(current.value);
Тут наверное previous.value нужно.

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/test/java/com/aytel/JTreapTest.java
> +    JTreap<Integer> treap;
private

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +            return true;
Если содержится, то false.

2019-02-23 20:57 UTC, RamSaw commented on hw3.kotlin/.idea/.name
> +hw
Тут у меня котлин уже пошел. Давайте делать PR так, чтобы не смешивались. Причем ниже идет код на джава, который я уже смотрел. Почему? Так и задумано?

2019-02-23 20:57 UTC, RamSaw commented on hw3.java/build.gradle
> +    compile 'org.codehaus.groovy:groovy-all:2.3.11'
А где Вы groovy используете?

2019-03-04 20:24 UTC, aytel commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +                    JTreap.this.remove(current.value);
Хм, а почему? previous -- это вершина, которую я последней прошёл. Если ещё ничего не прошёл или прошёл, но удалил, то она null, её удалять нельзя. Иначе удаляю.

2019-03-04 20:53 UTC, aytel commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +            return infoStorage.root.contains((T)element);
Разве я могу вообще такое проверить? В рантайме я потерял всю информацию о типах, instanceof я применить не могу. Что тут ещё можно сделать, кроме тупого каста? Может, не здесь, а в contains, но где-то точно придётся, разве нет?

2019-03-05 19:36 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +            return infoStorage.root.contains((T)element);
Да, Вы правы. Пожалуй, чтобы не заморачиваться и в точности скопировать поведение стандартного TreeSet можно так грубо кастовать и если что кидать ClassCastException. Но вообще даже для дженериков можно изловчиться через рефлексию.

2019-03-05 19:59 UTC, RamSaw commented
@aytel а Вы закончили исправлять?

2019-03-05 20:31 UTC, RamSaw requested changes
Я тут начал проверять, а потом подумал, что Вы еще может собирались что-то исправлять. В следующий раз упоминайте меня через @RamSaw , когда закончите.
Раз уж начал это ревью отправлю. Из прошлых замечаний Вы как минимум не сделали "добавьте тестов на все публичные методы".
Тимофей попросил сразу говорить Вам баллы, за что я снял:
-0.5 за ? super T, -1 за contains, который только предков может принять и -1 за юнит тесты, потому что вы не тестируете кучу методов. +2 за инвалидацию итератора добавил.
У Вас еще Travis упал, пофиксите, пожалуйста.

2019-03-05 20:31 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
>              return null;
first и last в этом случае кидают NoSuchElementException.

2019-03-05 20:31 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +    static class JListNode<T> {
мне кажется проще убрать статик и не надо будет T передавать

2019-03-05 20:31 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +        comparator = (T a, T b) -> ((Comparable<? super T>)a).compareTo(b);
На самом деле весь смысл Comparable<? super T> теряется. Потому что Вы сначала кастуете к типу T, а потом только добавляете возможность сравниваться за счет super.
В итоге у Вас contains и remove не могут принимать что-то отличное от предков T. А вообще должны. Я могу просто туда передать объект, который научу сравниваться с типом T или одним из его родителей и он должен отработать. Рекомендую, чтобы это реализовать присваивать компаратору null, если его нет.

2019-03-05 20:31 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
>      public boolean add(@NotNull T element) {
null может поддерживаться

2019-03-05 20:31 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +            return lower(element);
Вы нашли багу, а тесты не изменились. Значит плохие тесты. Добавьте еще, включая такой, чтобы бага не проходила тест.

2019-03-05 20:31 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +        comparator = (T a, T b) -> ((Comparable<? super T>)a).compareTo(b);
И добавьте тестов на это.

2019-03-05 20:31 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
>              return null;
и тестов на них нет. Добавьте на все публичные методы тестов.

2019-03-16 09:57 UTC, aytel commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +    static class JListNode<T> {
Ну у меня там static метод для соединения двух вершинок, а так я его вроде статиком сделать не смогу, так что вроде так логичнее.

2019-03-17 17:37 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +    static class JListNode<T> {
Так давайте его вынесем в самый верхний класс.
И по-моему там с областью видимости какие-то проблемы.
Этот класс и поля внутри него можно приватными сделать.

2019-03-18 21:56 UTC, aytel commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +        comparator = (T a, T b) -> ((Comparable<? super T>)a).compareTo(b);
Не очень понятно, почему я должен обрабатывать объекты, которые не являются потомками T, если у меня коллекция элементов T. Сейчас компаратор действительно написан плохо, я его сменил на Comparator.naturalOrder() и вроде вот это должно быть адекватным, но принимать вообще левые объекты я не хочу, так что contains и remove и должны ругаться, если им суют не T, имхо.

2019-03-18 21:58 UTC, aytel commented on hw3.java/src/main/java/com/aytel/JTreap.java
>      public boolean add(@NotNull T element) {
В смысле я должен поддерживать его хранение в коллекции? Это было бы странно, я ведь его не умею сравнивать на больше/меньше.

2019-03-18 22:14 UTC, aytel commented
@RamSaw 
Вот теперь почти всё пофиксил, а что не пофиксил -- по тому задал вопросы.

2019-03-19 22:25 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
>      public boolean add(@NotNull T element) {
можно же передать компаратор, который умеет сравнивать null

2019-03-19 22:28 UTC, aytel commented on hw3.java/src/main/java/com/aytel/JTreap.java
>      public boolean add(@NotNull T element) {
А если мне максимально не хочется хранить нуллы в своём дереве, то это плохо? По крайней мере в прошлых домашках нам разрешали и даже рекомендовали ругаться, если нас просят хранить нуллы в коллекциях. Здесь я никаких исключений не кидаю, но помечаю, что эта штука должна быть NotNull, вроде такого должно быть достаточно.

2019-03-19 22:29 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +        comparator = (T a, T b) -> ((Comparable<? super T>)a).compareTo(b);
но ведь contains и object принимают тип Object, а не T...
можно спорить и говорить, что это все тащиться из-за обратной совместимости и пожалуй логичней принимать T. Но все же на сегодня интерфейс другой и раз мы принимаем Object, то я могу передать MyString, который допустим научу сравниваться с Integer, просто интерпретируя строку как записанное число (если это не число, то пусть будет 0). Ну и вс корректно отработает.

2019-03-19 22:33 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
>      public boolean add(@NotNull T element) {
да, NotNull достаточно. Ладно, ок, пусть будет без null.

2019-03-19 22:38 UTC, RamSaw requested changes
@aytel все ок.
 в общем, исправьте contains и remove, и будет все полный ок.

2019-03-19 22:40 UTC, aytel commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +        comparator = (T a, T b) -> ((Comparable<? super T>)a).compareTo(b);
Тогда я не очень понимаю, какое поведение тут должно быть. Если этот MyString будет сравниваться с помощью компаратора, который мне передали, то я точно ломаюсь, потому что у меня Comparator<? super T>, который не умеет сравнивать MyString. Если с помощью метода compareTo у MyString, то я должен догадаться как-то этот метод вызывать, то есть не использовать компаратор, который сохранён у меня, и который может вообще противоречить компаратору у MyString, плюс Comparator.compare(integer, myString) и myString.compareTo(integer) могут давать странные результаты. Это точно то мозголомство, в которое стоит лезть?

2019-03-19 22:42 UTC, aytel commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +        comparator = (T a, T b) -> ((Comparable<? super T>)a).compareTo(b);
Я могу contains и remove сделать глупыми и работающими за линию, но это вряд ли то, что вы имеете в виду.

2019-03-19 22:46 UTC, RamSaw commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +        comparator = (T a, T b) -> ((Comparable<? super T>)a).compareTo(b);
Когда передан компаратор, то да, такое не сработает. Но если просто нам нужен тот, кто Comparable<T>, то сработает.
Поэтому надо разделить эти две логики. Присваивать в компаратор нулл, если его не передали.

2019-03-20 00:23 UTC, aytel commented on hw3.java/src/main/java/com/aytel/JTreap.java
> +        comparator = (T a, T b) -> ((Comparable<? super T>)a).compareTo(b);
Окей, переделал contains, remove и добавил вспомогательный метод у Node.

2019-03-20 20:11 UTC, RamSaw approved these changes
@aytel Ok
@jzuken

2019-03-21 19:47 UTC, merged