Hw4.java
aytel/javaHSE19 pull request #7
Opened 2019-02-27 04:15 UTC by aytel

2019-03-16 13:22 UTC, RamSaw requested changes
@aytel домашку проверил, упомяните как исправите.
Многие комментарии касаются не только строки, где он написан, но и других строк. Соответсвенно эти места тоже надо пофиксить.
Это к примеру \n и джавадоки неправильные.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/build.gradle
> +plugins {
Не прописан Main class, как следствие запуск jar файла из консоли невозможен.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/Main.java
> +        System.out.println(!phoneBook.add(name, number) ? "Ok, added\n" : "Already added to phonebook.");
\n наверное забыли у Already added to phonebook

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/Main.java
> +        String number = read("number");
Давайте назовем phoneNumber, а то можно подумать, что это число (у меня так и случилось).

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/Main.java
> +        String number = read("number");
Ну и всех записей ниже тоже касается

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/PhoneBook.java
> +        datastore.getDB().dropDatabase();
а зачем дропать всю базу данных?

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/Ownership.java
> +        this.name = "John Cena";
а что эти значения значат и откуда они взялись?

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/PhoneBook.java
> +        datastore.ensureIndexes();
А Вы читали как MongoDB делает индексирование? я просто почитал немного и на stackoverflow говорят, что индексирование само делается. Я просто к тому, что может неоптимально делать самому индексы, ибо не всегда они работают быстрее.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/PhoneBook.java
> +        datastore.ensureIndexes();
Лучше наверное отдать это на откуп базе данных. Но я не специалист по MongoDB, поэтому хотелось бы услышать Ваше мнение.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/Ownership.java
> +    public boolean equals(Object other) {
hashCode добавьте тогда.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/Ownership.java
> +/** Simple class, containing name of owner and his phone number.
перенос строки нужен, это не однострочный коммент же. -0.5

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/Ownership.java
> +        this.name = "John Cena";
и конструктор вообще не используется

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/Main.java
> +
пустая строка.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/PhoneBook.java
> +    /** Adds new {@link Ownership} to database. Returns true if there was such element and false otherwise. */
для этого есть тэг return.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/PhoneBook.java
> +    /** Adds new {@link Ownership} to database. Returns true if there was such element and false otherwise. */
а вообще обычно возвращают true если реально был добавлен и false если уже был

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/PhoneBook.java
> +        return false;
А тут с true false все ок? У Вас там если false, то вы пишете "already exists", но по факту то не так.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/PhoneBook.java
> +        return false;
Мне кажется надо возвращать true, если действие было осуществеленно (в данном случае реально произошел update, false в противном случае.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/PhoneBook.java
> +                "name",
очень часто дублируется. Я думаю стоит у OwnerShip сделать просто статические поля, которые содержат эти строки. Ну и если бы так было сделано, то поменять с number на phoneNumber не составила труда :)

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/Main.java
> +    private static void updateNumber() {
updateNumber и UpdateName можно вынести общий метод из них, как Вы это сделали в PhoneBook классе.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/test/java/com/aytel/PhoneBookTest.java
> +        phoneBook.add("a", "10");
а ну теперь понятно зачем дропать базу надо было. Давайте в тестах сделаем After и там будем чистить, что нам надо. А то у Вас приложение получается, которое после закрытия не сохраняет состояние.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/PhoneBook.java
> +        datastore.getDB().dropDatabase();
Пока что -1, если Вы не объясните зачем так делать и почему это нормально.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/test/java/com/aytel/PhoneBookTest.java
> +        List<Ownership> list = phoneBook.getAll();
неиспользуемая переменная. -1
я тут -1 в совокупности поставил за неаккуратное форматирование. Я учел еще здесь пустую строчку и то, что у Вас не используемый конструктор со странными значениями полей.
Кстати если оставите его, добавьте к нему комментарий, поясняющий зачем он нужен.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/test/java/com/aytel/PhoneBookTest.java
> +        assertFalse(phoneBook.updateName("a", "10", "b"));
нет давайте возвращать все же везде, где действие произошло как и ожидалось true. Уж очень странно это смотрится. Это всех мест с true/false касается.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/test/java/com/aytel/PhoneBookTest.java
> +        List<Ownership> list = new ArrayList<>();
var. -0.5.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/test/java/com/aytel/PhoneBookTest.java
> +        List<Ownership> list = new ArrayList<>();
Там были еще места, где можно было ставить var. Ощущение, что Вы про него забыли.

2019-03-16 13:22 UTC, RamSaw commented on hw4.java/src/test/java/com/aytel/PhoneBookTest.java
> +    void update() {
updateNumber не тестируется.
разделите эти тесты на 2.
-0.5

2019-03-18 22:21 UTC, aytel commented on hw4.java/src/main/java/com/aytel/Ownership.java
> +        this.name = "John Cena";
Это Mongo хочет обязательно конструктор по умолчанию для объектов, которые в ней лежат, и даже его где-то использует, поэтому кидать исключение не выйдет. Окей, помечу, зачем это нужно.

2019-03-18 22:36 UTC, aytel commented on hw4.java/src/main/java/com/aytel/PhoneBook.java
> +        datastore.getDB().dropDatabase();
Ну да, это было для тестов плюс по умолчанию не предполагал, что с базой надо работать дольше, чем в одном вечном цикле -- запустились, поработали, закончили. Но да, это странно, наверное. fixed.

2019-03-18 23:03 UTC, aytel commented on hw4.java/src/main/java/com/aytel/Main.java
> +    private static void updateNumber() {
Нет, это вряд ли очень удобно. В этих двух методах я разное спрашиваю у пользователя -- в PhoneBook я мог просто передать четыре значения, а тут это наверняка скатится в ифы, так что кода только больше станет. Да и копипасты тут минимум, так что я бы не менял.

2019-03-18 23:05 UTC, aytel commented on hw4.java/src/main/java/com/aytel/PhoneBook.java
> +        datastore.ensureIndexes();
Я пока опытным путём выяснил, что если понадеяться, что Mongo всё сделает сама, то она начинает выдавать в поиске те самые Ownership'ы, сделанные конструктором по умолчанию. Я не очень понимаю, как это работает, так что лучше не буду ломать.

2019-03-20 20:32 UTC, RamSaw requested changes
@aytel посмотрел
осталось пару вопросов
конфликт с мастером пофиксите пожалуйста еще.

2019-03-20 20:32 UTC, RamSaw commented on hw4.java/src/main/java/com/aytel/Ownership.java
>          this.name = "John Cena";
не, тогда уж null туда кладите. Зачем туда писать какое-то вообще непонятно откуда взявщееся значение?

2019-03-20 20:32 UTC, RamSaw commented on hw4.java/build.gradle
> +mainClassName = 'com.aytel.Main'
`./gradlew jar`
`java -jar build/libs/hw-1.4.0.jar`
`no main manifest attribute, in build/libs/hw-1.4.0.jar`
Либо не работает, либо я что-то делаю не так.

2019-03-20 20:37 UTC, aytel commented on hw4.java/build.gradle
> +mainClassName = 'com.aytel.Main'
Хм. Я просто main запускал через gradlew run и это работает.

2019-03-20 20:40 UTC, aytel commented on hw4.java/src/main/java/com/aytel/Ownership.java
>          this.name = "John Cena";
Ну. Потому что при правильной работе Mongo эта штука вообще нигде не вылезет (тем более что этот конструктор приватный и такой Ownership никто не создаст), почему бы и не оставить шутку. Пофиксить нетрудно, но так ли уж это нужно, раз этим никто не пользуется и тут написано, зачем такая штука вообще нужна?)

2019-03-21 19:37 UTC, jzuken commented on hw4.java/src/main/java/com/aytel/Main.java
> +    private static String HELP =
ну вообще так константы именуются по стайлгайду

2019-04-22 13:03 UTC, merged