Hw5.java
aytel/javaHSE19 pull request #9
Opened 2019-03-12 13:01 UTC by aytel

2019-03-17 18:42 UTC, jzuken requested changes

2019-03-17 18:42 UTC, jzuken commented on hw5.java/src/test/java/com/aytel/ReflectorTest.java
> +    void dumb() throws IOException {
что это за тест без ассертов?

2019-03-17 18:42 UTC, jzuken commented on hw5.java/src/main/java/com/aytel/Reflector.java
> +        printMethodsOnlyInFirst(firstClass, secondClass);
а давайте в метод вынесем, два раза одно и то же повторяется же

2019-03-17 18:42 UTC, jzuken commented on hw5.java/src/main/java/com/aytel/Reflector.java
> +        stringBuilder.append("(").append(Arrays
и тут тоже копипаста
-1

2019-03-19 10:48 UTC, aytel commented
@jzuken 
Всё пофиксил.

2019-03-21 19:39 UTC, merged